### ISSUE TITLE
Greg's quote overruns bounding box

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain/marketing#12]
https://www.rchain.coop/leadership the word "content" in the first line of the quote extends beyond the maroon box that frames it.
![image](https://user-images.githubusercontent.com/2915325/45645724-6016d980-ba8f-11e8-8279-b74146a5a4a2.png)

**Comment by bjornagain** [comment]
@JoshOrndorff this is fixed. Please review: https://www.rchain.coop/leadership

**Comment by JoshOrndorff** [comment]
Looks great @bjornagain . Thanks!
