### ISSUE TITLE
Link to membership page

### ISSUE THREAD

**Issue by n10n** [rchain/marketing#13]
https://member.rchain.coop/ and need somebody to work with Ian and I.

**Comment by bjornagain** [comment]
Where should I put the link?

**Comment by JoshOrndorff** [comment]
I would suggest either:
1. In the Header with {Home, Platform, Community} or under the Community dropdown. Anchor text could be "Members Area" or "Become a Member".

**Comment by JoshOrndorff** [comment]
If we label it "become a member" it would also solve #6

**Comment by n10n** [comment]
Replace "Get Started" on the top right to "Join Membership", for now. We don't need two "Get Started" button few inches apart on front page. We need to discuss this more considering we want to provide an integrated experience with "membership" site in coming days.

**Comment by JoshOrndorff** [comment]
Slightly off topic: Who is @n10n ?

**Comment by bjornagain** [comment]
Should i implement @n10n's suggestion?

**Comment by JoshOrndorff** [comment]
@bjornagain I'm assigning this to you. Code it up as you see best fit. We trust your judgement.

I'm fine taking @n10n 's suggestion or adding it to the top bar. I agree that this is urgent. It's hard to figure out how to join.

**Comment by bjornagain** [comment]
@JoshOrndorff  @n10n 
The nav button now says 'Join Membership' and links to the member site signup page.
