### ISSUE TITLE
blog category just for weekly debrief items

### ISSUE THREAD

**Issue by dckc** [rchain/marketing#17]
Please collect these in a blog category:

https://blog.rchain.coop/rchain-update-94-feedback-from-rcon3/
https://blog.rchain.coop/rchain-debrief-93-rcon3/
https://blog.rchain.coop/rchain-debrief-92-rcon3-week/
etc.

Perhaps you could make use of this index, which goes back to May 2017
https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index

**Comment by bjornagain** [comment]
Is this a request for a change to the blog, or rchain.coop?

**Comment by dckc** [comment]
to the blog, I guess.

It's a request for a tag or category or whatever where I can find all and only the weekly debrief items.

**Comment by bjornagain** [comment]
This repo is just for rchain.coop. Try reaching out to Suku on Discord to see about blog changes.

**Comment by JoshOrndorff** [comment]
We haven't used this issue queue for things other than the website so far, although we will for other assets in the future. Let's ping @plantether here so she can think about that blog category too.

**Comment by plantether** [comment]
@dckc Done.
