### ISSUE TITLE
The old /events URL is 404

### ISSUE THREAD

**Issue by kitblake** [rchain/marketing#2]
On the old RChain site, https://www.rchain.coop/events was a redirect to https://developer.rchain.coop/conference. It's now a 404. Can we create a redirect? 
@bjornagain @KWattage @JoshOrndorff

**Comment by kitblake** [comment]
This has been fixed.

**Comment by JoshOrndorff** [comment]
The redirect is nice, and a much needed fix. But isn't info about the conference interesting to a more general audience than developers? Any reason that content should be hosted on developer.rchain.coop rather than the main rchain.coop?
