### ISSUE TITLE
Add compelling thumbnail to homepage video

### ISSUE THREAD

**Issue by pmoorman** [rchain/marketing#25]
Nuno pointed out (as I had noticed myself) that the video no the homepage displays as a black screen when it's not playing.

We need to provide a compelling thumbnail, or maybe make it autoplay or something like that. 

(@bjornagain could you have a look at this one?)

**Comment by bjornagain** [comment]
@pmoorman I set it to autoplay. If you prefer a thumbnail just get me the image to use and I'll make the change.

**Comment by pmoorman** [comment]
At least the black block is gone, so as far as I'm concerned this is done.  :-)

I imagine it might annoy some people that the video autoplays including the sound. **Maybe disable default sound for it?**

**Comment by JoshOrndorff** [comment]
My preferences in order are:

1. Don't autoplay, but use this thumbnail
![image](https://user-images.githubusercontent.com/2915325/46173414-2eaec280-c274-11e8-9556-20212f257403.png)

2. Do autoplay on mute

3. Do autoplay with sound

4. Black square.

**Comment by kitblake** [comment]
I second the motion to do number 1.

**Comment by bjornagain** [comment]
@SethPyrofex

**Comment by SethPyrofex** [comment]
@bjornagain @JoshOrndorff @pmoorman Video thumbnail added and autoplay disabled. 
https://www.rchain.coop/
