### ISSUE TITLE
Broken link to pizzaOrder.rho

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain/marketing#29]
There is a link from https://www.rchain.coop/learn-rholang to https://www.rchain.coop/pizzaOrder.rho that doesn't go anywhere. That code was supposed to be inlined.

This will ultimately be fixed if #3 lands, but in the meantime, we should fix this acute issue.

**Comment by bjornagain** [comment]
@JoshOrndorff  this code is now inline. Please review.

**Comment by JoshOrndorff** [comment]
Thanks :) @bjornagain
