### ISSUE TITLE
Events link on main site goes to RCon3

### ISSUE THREAD

**Issue by derekberes** [rchain/marketing#35]
Would be fine to file as "previous events," but right now still presents RCon3 as "in the future." A calendar option would be great, so that people understand we have events in the future, such as the Board elections. That way we can have future events and previous events listed, so there is a history of what we've accomplished but people recognize that we have future events.

**Comment by kitblake** [comment]
This could be merged with #5. Your call @derekberes..

**Comment by derekberes** [comment]
Events link removed for now. New page being requested soon. Closing this.
