### ISSUE TITLE
Old blue logo still on Coop page

### ISSUE THREAD

**Issue by derekberes** [rchain/marketing#36]
Near the bottom: https://www.rchain.coop/rchain-cooperative

**Comment by JoshOrndorff** [comment]
That's actually the new blue blue logo. That blue is one of our secondary colors. If it ended up there, it must have been in the wireframe.

Does anyone know who would actually be responsible for making that change?

**Comment by derekberes** [comment]
Hey @JoshOrndorff do you have the Girvin guidelines? According to what I'm reading, that blue is part of the "Extended Color Palette," which includes the following instructions: "The extended color palette offers a sophisticated approach to a pop color. These options go well with the RChain primary palette and still carry a premium feel to elevate the brand. These colors should be used as CTA buttons on the website, icon treatments and other smaller, secondary components of RChain branding." 

A few pages later, on the page, "The Do Nots," it says, "Consistent application of the logo is crucial to brand integrity and recognition. To the right we have laid out some examples of how the logo should not be used. Again, this is all for the sake of strengthening your brand through consistency." Then, specific to the logo, "Do not use colors other than the primary brand colors." Blue is listed as a secondary color, and there is even an image of a blue logo under "do not." 

I've been using this document as the final say in branding. If that's changed, please let me know, but I've seen some discussions on Discord about wrong logo usage, and it was my understanding that blue was out.

**Comment by kitblake** [comment]
Looks like this has been fixed, closing.
