### ISSUE TITLE
RChain blog Header not click-able 

### ISSUE THREAD

**Issue by Ojimadu** [rchain/marketing#40]
The RChain blog header isn't click-able. Ordinarily I suppose there header should be click-able and link to the blog homepage (https://blog.rchain.coop). As it stands now, there's no homepage button on the sidebar and the header is not click-able so the only way to navigate back to the home page is by inputting the address again on the address bar.
@bjornagain? @Andrekuipers?

**Comment by kitblake** [comment]
This has been fixed by @Andrekuipers.
