### ISSUE TITLE
Mute sound, or suppress auto-play, for video on main page of rchain.coop

### ISSUE THREAD

**Issue by glenbraun** [rchain/marketing#42]
A visitor to rchain.coop will hear a stream of audio immediately upon vising the page. This is probably not something people who visit the page from a less than private (like work) location. Mute the sound, or stop the auto-play.

**Comment by bjornagain** [comment]
@glenbraun  @PatrickM727  I have muted the video, but it still autoplays.

**Comment by kitblake** [comment]
Closing, reopen if the video shouldn't autoplay (+1).
