### ISSUE TITLE
Fix https certificate on member site. 

### ISSUE THREAD

**Issue by Ojimadu** [rchain/marketing#45]
The security certificate for the [member site](member.rchain.coop) just expired on 03/10/18 and needs to be updated.

@kitblake

**Comment by David405** [comment]
@Ojimadu please update the link you provided

**Comment by JoshOrndorff** [comment]
The relevant people, fixed this.

**Comment by kitblake** [comment]
Thanks to the relevant people, and @Ojimadu for the nudge.
