### ISSUE TITLE
rchain.coop typos and minor proofreading fixes

### ISSUE THREAD

**Issue by plantether** [rchain/marketing#8]
HOME PAGE:
Dependable and Secure for **all** Applications --> Dependable and Secure for **All** Applications

Engage with the Community
... lifting our world up and **affecting** real, positive change, we will help each other flourish. -->
... lifting our world up and **effecting** real, positive change, we will help each other flourish.

[bottom of page]
Ready to **Affect** Change?   -->  Ready to **Effect** Change?

---------------------

The RChain Platform

CURRENT STATE
...Sequential computing inevitably limits scalability and speed, while **increases** transaction costs
-->
Sequential computing inevitably limits scalability and speed, while **increasing** transaction costs

Massive energy and computational requirements **have left the promise of decentralized mass adoption unrealized.**   [Seems like an overstatement]
-->
Massive energy and computational requirements **are major obstacles to mass adoption of decentralized systems.**

NAMESPACES
Namespaces, virtual groups of **Rnodes** within the **Rchain** network...   -->
Namespaces, virtual groups of **RNodes** within the **RChain** network...

Next-generation sharding divides the network into optimized pieces, solving for the **racing** condition 
-->
Next-generation sharding divides the network into optimized pieces, solving the **race** condition 

Rholang
... Rholang is natively executed by **Rnodes**  --> Rholang is natively executed by **RNodes** 

-----------------------
Community Overview
The Power of the Cooperative
...allowing anyone with an interest to **affect** our movement  
--> 
allowing anyone with an interest to **contribute to** our movement

-----------------------------
Leadership page

RChain Cooperative
...for RChain to grow **into, to** remain, a publicly owned and operated information **utility.RChain**  
-->
for RChain to grow **into, and** remain, a publicly owned and operated information **utility. RChain** 

RChain Cooperative members **form decentralized autonomous organization**.
(Sounds a little awkward because it feels like there should be an "s" on the end of "organization", but I think it's meant to be as is. Could "create" be used instead of "form"?)
RChain Cooperative members **create** decentralized autonomous organization.
or rephrase as something like:
Cooperation leads to the emergence of decentralized autonomous organization.

**Comment by JoshOrndorff** [comment]
I've corrected these issues in f8f4aa52eb2e2a365c67dc68203aaea314be4895

Regarding the very last one, should we avoid the phrase "decentralized autonomous organization" entirely? That's a buzz word in the smart contract industry. That what DAO and in "the DAO" stands for. Although we are certainly decentralized and an organization, and in some sense autonomous, we aren't the very specific smart-contract-governed DAO that many will think of when reading that.

**Comment by JoshOrndorff** [comment]
Closing because the live site has this fix in place.

**Comment by JoshOrndorff** [comment]
Oops, no it doesn't. @bjornagain Can you please get these changes live?

**Comment by bjornagain** [comment]
These fixes should be up, via Joshy's edits. Please review.

**Comment by JoshOrndorff** [comment]
Looks good to me. Closing.

@plantether Review and reopen if you like.
